stack: jussi/tensorflow-example
version: 1.3.0
description: Tensorflow inception service
variables:
  lb_service:
    type: string
    from:
      env: LOADBALANCER
      service_link:
        prompt: Pick a loadbalancer
        image: kontena/lb

  vhost:
    type: string
    from:
      env: API_VHOST
      prompt: Virtual host for loadbalancing

services:
  api:
    image: jnummelin/tensor-inception:latest
    links:
      - {{ lb_service }}
    environment:
      TF_ADDRESS: "serving:9000"
      KONTENA_LB_VIRTUAL_HOSTS: {{ vhost }}
      KONTENA_LB_INTERNAL_PORT: 8080
    # ports:
    #   - "8080:8080"

  serving:
    # Model pre-imported into the image
    image: jnummelin/tensorflow-serving-inception:latest
